---
# tasks file for mysql_db       
      - name: Install mysql 
        apt: 
              name: "{{ item }}" 
              state: present
        with_items: 
            - mysql-server
            - mysql-client

      - name: start mysql service
        service: 
              name: mysql
              state: started   
              enabled: yes

      - name: Create application database
        mysql_db: 
              name: "{{ db_name }}" 
              state: present

      - name: Create application db user
        mysql_user: 
             name: "{{ db_user }}"
             password: "{{ db_password }}"
             priv: '*.*:ALL'
             host: '%'
             state: present
